#!/usr/bin/env bash
set -euo pipefail
# Starfare design-doc commit: Syndicate BUY delivery model + craft speed.
# Run from repo root: gitserver@gitserver:/mnt/git-server/starfare  (does NOT push)
test -f docs/design.md || { echo "!! run me from the starfare repo root"; exit 1; }

# --- 1. edits (fail-loud, base64 anchors so UTF-8 is copy-safe) ---
python3 - <<'PYEOF'
import base64
banner = base64.b64decode("IyMjIFN5bmRpY2F0ZSBQdWJsaWMgVHJhbnNwb3J0Cgo+ICoqU1VQRVJTRURFRCBmb3IgdGhlIFNFTEwgc2lkZSAoMjktMDgtMjYpLioqIFRoZSBzdWJzZWN0aW9uIGJlbG93IGRlc2NyaWJlcyB0aGUgU3luZGljYXRlIGhhdWxpbmcgZ29vZHMgYSBndWlsZCBpcyAqKnNlbGxpbmcqKiDigJQgYSByb3VuZCB0cmlwIHdpdGggYSBmZWUsIHRoZSBlYXJseS1nYW1lIG9uLXJhbXAgZm9yIHNoaXBsZXNzIGd1aWxkcy4gVGhhdCBtb2RlbCBpcyAqKnJldGlyZWQqKjogc2VsbGluZyB0byB0aGUgU3luZGljYXRlIGlzIG5vdyAqKmluc3RhbnQgYW5kIGZyaWN0aW9ubGVzcyoqICjCpzUsICJTRUxMIEdPRVMgTElWRSIpIOKAlCB0aGUgU3luZGljYXRlIGNvbGxlY3RzIGluIHBsYWNlLCBub3RoaW5nIHNoaXBzLCBubyBmZWUuIFN5bmRpY2F0ZSB0cmFuc3BvcnQgbm93IHNlcnZlcyB0aGUgKipCVVkqKiBzaWRlIG9ubHkgKG5leHQgc3Vic2VjdGlvbikuIFRoZSByb3VuZC10cmlwIC8gZmVlIC8gU3luZGljYXRlLUhhdWxlci1waXJhY3kgZGV0YWlsIGJlbG93IGlzIGtlcHQgZm9yIGhpc3Rvcnk7IHRoZSBpbnRlcmNlcHRpb24sIHRvbGxzLCBhbmQgcmVhbGl6ZWQtb24tYXJyaXZhbCBydWxlcyBpdCBzaGFyZXMgd2l0aCDCpzYncyBpbnRybyByZW1haW4gbGl2ZSBmb3IgdGhlICoqZ3VpbGQtb3duZWQqKiB0cmFuc3BvcnQgdGllciwgbm90IHRoZSBTeW5kaWNhdGUgb25lLiAqKkZsYWdnZWQsIG5vdCByZXNvbHZlZDoqKiBpbnN0YW50IFNFTEwgaXMgYSAiZ29vZHMgbW92ZSBmcmVlIiBjYXNlLCB3aGljaCDCpzUgKHRoZSBWTy10cmFuc3BvcnQgcnVsaW5nKSBhbmQgwqc4IGxlYW4gKmFnYWluc3QqIHRvIHByb3RlY3QgdGhlIGZ1ZWwgbWFya2V0LCBhbmQgaXQgcmVtb3ZlcyB0aGUgdmVoaWNsZS1nYXRlIFNFTEwgb24tcmFtcCB0aGlzIHNlcnZpY2UgcHJvdmlkZWQgKMKnMTMsIG9wZW4gIzgpIOKAlCBhIGxpdmUgdGVuc2lvbiB0byByZWNvbmNpbGUgZGVsaWJlcmF0ZWx5LCB0cmFja2VkIGFzIGFuIG9wZW4gdGhyZWFkLgo=").decode("utf-8").rstrip("\n")
buysub = base64.b64decode("IyMjIFN5bmRpY2F0ZSBEZWxpdmVyeSDigJQgdGhlIEJVWSBzaWRlICooMjktMDgtMjYpKgoKKipUd28gdHJhbnNwb3J0IHRpZXJzLCBhbmQgdGhleSBtdXN0IG5vdCBiZSBjb25mdXNlZC4qKiAqU3luZGljYXRlKiB0cmFuc3BvcnQgaXMgYSAqKnNlcnZpY2UqKiB0aGUgcGxheWVyIGRvZXMgbm90IHBsYW46IGEgKipzdHJhaWdodCBsaW5lKiosIGhleCB0byBoZXgsIGF0IGEgZml4ZWQgc3BlZWQsIHdpdGggKipubyByaXNrLCBubyB0b2xscywgbm8gcm91dGluZyoqIOKAlCB0aGUgU3luZGljYXRlIGhhcyBpdHMgb3duIHdheXMuIFRoaXMgaXMgd2hhdCBCVVkgdXNlcywgYW5kIHRoZSBvbmx5IHRyYW5zcG9ydCBidWlsdCBpbiBQaGFzZSAxLiAqR3VpbGQqIHRyYW5zcG9ydCBpcyBhICoqcGxheWVyIHNraWxsKiog4oCUIHJvdXRpbmcgeW91ciBvd24gY3JhZnQgbGVnIGJ5IGxlZyB0aHJvdWdoIHNhZmUgc3BhY2UsIHRvbGxzLCBhbmQgaG9zdGlsZSB0ZXJyaXRvcnkg4oCUIHRoZSDCpzYtaW50cm8gbW9kZWwsICoqZGVmZXJyZWQgdG8gUGhhc2UgNCoqLiBUaGUgYm91bmRhcnkgaXMgbmFtZWQgc28gbm9ib2R5IHJlYnVpbGRzIHRoZSByb3V0aW5nIGVuZ2luZSB3aGVuIFN5bmRpY2F0ZSB0cmF2ZWwgb25seSBuZWVkcyBhIHN0cmFpZ2h0IGxpbmUgKHRoZSBzYW1lIGRpc2NpcGxpbmUgYXMgdGhlIENIT0FN4oaSU3luZGljYXRlIGNvbnNvbGlkYXRpb24pLgoKKipUaGVyZSBpcyBubyBwaHlzaWNhbCBzaGlwbWVudCB0byBzaW11bGF0ZSDigJQgb25seSBhIHNjaGVkdWxlZCBkZWxpdmVyeS4qKiBXaGVuIHRoZSBwbGF5ZXIgY29uZmlybXMgYSBCVVksIHRoZSBlbmdpbmU6CgoxLiByZXNvbHZlcyB0aGUgKipuZWFyZXN0IFN5bmRpY2F0ZSB3YXlzdGF0aW9uKiogdG8gdGhlIGNob3NlbiBkZXN0aW5hdGlvbiBzeXN0ZW0g4oCUIGhleCBkaXN0YW5jZSBvdmVyIHRoZSBzZWVkJ3MgYXhpYWwgYGNvb3Jkc2A7CjIuIGNvbXB1dGVzIGBhcnJpdmFsVGljayA9IGN1cnJlbnRUaWNrICsgY2VpbChoZXhEaXN0YW5jZSDDlyBDUkFGVF9TUEVFRClgIChjcmFmdCBzcGVlZCBpcyBgW0ZJUlNULUNVVF1gIGluIGBkb2NzL3BoYXNlLTEtdHVuaW5nLm1kYCk7CjMuICoqZGViaXRzIHRoZSBjYXNoIG5vdyoqIOKAlCBgcXR5IMOXIHBvc3RlZFByaWNlYCwgdGhlICpzYW1lIHNpbmdsZSBwcmljZSBhIHNhbGUgZWFybnMqICgjNDMpLCAqKm5vIHRyYW5zcG9ydCBmZWUqKiAodGhlIFN5bmRpY2F0ZSBjaGFyZ2VzIGZvciBjb250cm9sLCBub3QgY2FycmlhZ2Ug4oCUIMKnNSdzIG5vLXNwcmVhZCBydWxlKSwgY3JlZGl0ZWQgdG8gYHN5bmRpY2F0ZS5sZWRnZXJgIHNvIGludmFyaWFudCAyIGhvbGRzOyBhbmQKNC4gcmVjb3JkcyBhICoqcGVuZGluZyBkZWxpdmVyeSoqIGluIHRoZSBJTi1GTElHSFQgbGF5ZXIgKGBzdGF0ZS5zaGlwbWVudHNgLCDCpzE1LjEpOiBgeyBjYXJnbzogeyBbZ29vZF06IHF0eSB9LCBkZXN0aW5hdGlvblN5c3RlbUlkLCBhcnJpdmFsVGljayB9YCDigJQgKipubyBvcmlnaW4sIG5vIHJvdXRlLCBubyBzdGF0dXMqKiwgYmVjYXVzZSBub3RoaW5nIG5lZWRzIHRyYWNraW5nIGJldHdlZW4gbm93IGFuZCBhcnJpdmFsICjCpzE1LjYncyAicHVyZSBzY2hlZHVsZSI6IGEgZGVsaXZlcnkgb24gYW4gdW5jb250ZXN0ZWQgc3RyYWlnaHQgbGluZSBuZWVkcyBubyBwZXItdGljayB3b3JrIHVudGlsIGl0IGxhbmRzKS4KCioqRGVsaXZlcnkgaXMgYSB0aWNrIHN0ZXA6KiogYW55IHBlbmRpbmcgZGVsaXZlcnkgd2hvc2UgYGFycml2YWxUaWNrYCBoYXMgYXJyaXZlZCBkZXBvc2l0cyBpdHMgY2FyZ28gaW50byB0aGUgZGVzdGluYXRpb24gc3lzdGVtJ3Mgc3RvY2twaWxlIGFuZCBkcm9wcyBvZmYgdGhlIGxpc3QuIEJlY2F1c2UgdGhlIHJlY29yZCBsaXZlcyBpbiB0aGUgc2F2ZSBhbmQgdGhlIGFycml2YWwgaXMgYW4gKiphYnNvbHV0ZSoqIHRpY2ssIGEgcmVzdGFydCBtaWQtZmxpZ2h0IHJlbG9hZHMgaXQgYW5kIGl0IHN0aWxsIGxhbmRzIG9uIHRoZSByaWdodCB0aWNrIOKAlCAqKnBlcnNpc3RlbmNlIGlzIHRoZSBtaWQtZmxpZ2h0IGhhbmRsaW5nKiosIG5vIHNwZWNpYWwgY2FzZS4KCioqT25lIHNoaXBtZW50LCBvbmUgZGVzdGluYXRpb24sIG5vIHNwbGl0dGluZyoqICjCpzUpOiBhIHB1cmNoYXNlIGdvZXMgdG8gZXhhY3RseSBvbmUgc3lzdGVtLCB1bmxpa2UgYSBzYWxlIHRoZSBwbGF5ZXIgc3BsaXRzIGFjcm9zcyBzb3VyY2VzIOKAlCB0aGUgZGVsaWJlcmF0ZSBhc3ltbWV0cnkgKGEgc2FsZSBpcyBpbnN0YW50LCBzbyBpdCBjYW4gcGljay1hbmQtbWl4OyBhIGRlbGl2ZXJ5IHRyYXZlbHMsIHNvIGl0IGNvbW1pdHMgdG8gb25lIHBsYWNlKS4KCioqRGVzdGluYXRpb24gbG9zdCBpbiBmbGlnaHQg4oaSIHRoZSBnb29kcyB2YW5pc2guKiogSWYsIGF0IHRoZSBhcnJpdmFsIHRpY2ssIHRoZSBidXlpbmcgZ3VpbGQgbm8gbG9uZ2VyIGhvbGRzIHRoZSBkZXN0aW5hdGlvbiBzeXN0ZW0sIHRoZSBjYXJnbyBpcyAqKmxvc3Qg4oCUIGNvbnRhY3Qgd2l0aCB0aGUgY3JhZnQgaXMgbG9zdCoqOiBubyByZWZ1bmQsIG5vIGRpdmVydC4gVGhpcyBpcyBjb25zZXJ2YXRpb24tY2xlYW4g4oCUIHRoZSBnb29kcyB3ZXJlIG5ldmVyIGluIGEgc3RvY2twaWxlIChhIHNjaGVkdWxlZCBkZXBvc2l0LCBub3QgaGVsZCBpbnZlbnRvcnkpLCBhbmQgdGhlIGNhc2ggYWxyZWFkeSBtb3ZlZCB0byB0aGUgbGVkZ2VyIGF0IHB1cmNoYXNlLCBzbyBkcm9wcGluZyB0aGUgZGVsaXZlcnkgaW1iYWxhbmNlcyBub3RoaW5nLiBJdCBpcyBhbHNvIHJlYWwgcHJlc3N1cmU6IGJ1eWluZyBpbnRvIGEgc3lzdGVtIHlvdSBjYW5ub3QgaG9sZCBpcyBhIHJpc2sgeW91IG93bi4gKFRoZSBwcmVjaXNlIHRyaWdnZXIg4oCUIHdoYXQgIm5vIGxvbmdlciBob2xkcyIgbWVhbnMgYWdhaW5zdCB0aGUgb3duZXJzaGlwL2NsYWltcyBtb2RlbCDigJQgaXMgcGlubmVkIGF0IGJ1aWxkIHRpbWU7IHRoZSAqKm91dGNvbWUqKiBpcyBydWxlZC4pCgoqKkZ1ZWwgaW52YXJpYW50IG5vdGU6KiogYSBCVVkgZGVsaXZlcnkgY2FycmllcyAqKm5vbi1mdWVsKiogZ29vZHMsIHNvIGl0IG11c3QgY29udHJpYnV0ZSAqKnplcm8qKiB0byB0aGUgZnVlbC1pbi10cmFuc2l0IHN1bSBpbnZhcmlhbnQgMSB0cmFja3MgKMKnMTUpIOKAlCBpdHMgYGNhcmdvYCBzaGFwZSBjYXJyaWVzIHRoZSBib3VnaHQgZ29vZCwgbmV2ZXIgYSBzcHVyaW91cyBgZnVlbGAgZmllbGQuCg==").decode("utf-8").rstrip("\n")
tune   = base64.b64decode("LSAqKlN5bmRpY2F0ZSBjcmFmdCBzcGVlZCoqIGBbRklSU1QtQ1VUXWAgKDI5LTA4LTI2KTogKiozMDAgdGlja3MgcGVyIGhleCoqICg1IGhvdXJzIGF0IDEgdGljayA9IDEgbWludXRlKS4gQSBTeW5kaWNhdGUgQlVZIGRlbGl2ZXJ5IHRyYXZlbHMgdGhlIG5lYXJlc3Qtd2F5c3RhdGlvbuKGkmRlc3RpbmF0aW9uIHN0cmFpZ2h0LWxpbmUgaGV4IGRpc3RhbmNlIGF0IHRoaXMgcmF0ZTogYGFycml2YWxUaWNrID0gYnV5VGljayArIGNlaWwoaGV4RGlzdGFuY2Ugw5cgMzAwKWAuIEEgb25lLWhleCBkZWxpdmVyeSBsYW5kcyBpbiA1IGhvdXJzLCBhIGZvdXItaGV4IG9uZSBpbiBtb3N0IG9mIGEgY3ljbGUg4oCUIHRoZSBmcmljdGlvbiB0aGF0IG1ha2VzIEJVWSBhICpwbGFubmVkKiBhY3QgYWdhaW5zdCBpbnN0YW50IFNFTEwuIERpc3RpbmN0IGZyb20gKipUcmFuc2l0IHRpY2tzIHBlciBlZGdlKiogYWJvdmUgKHRoZSBndWlsZC1yb3V0ZWQsIHBlci1sZWcgbnVtYmVyKTsgdGhlIHR3byBzaG91bGQgc3RheSBpbiBzaWdodCBvZiBlYWNoIG90aGVyIHdoZW4gdGhlIGd1aWxkIHRpZXIgaXMgdHVuZWQuIENob3NlbiBhcyBhIGZpcnN0IHBhc3MsIHRvIGJlIGZlbHQgYWdhaW5zdCByZWFsIGRlbGl2ZXJpZXMgYW5kIHJldHVuZWQ7IGNoYW5naW5nIGl0IGlzIHRoaXMgb25lIGxpbmUuCg==").decode("utf-8").rstrip("\n")

p="docs/design.md"; s=open(p,encoding="utf-8").read()
hdr="### Syndicate Public Transport\n"
assert s.count(hdr)==1, f"design.md: header count={s.count(hdr)} (expected 1)"
s=s.replace(hdr, banner+"\n", 1)
a7="\n## 7. Politics and Law: The Council, Legality, and Fines"
assert s.count(a7)==1, f"design.md: section-7 anchor count={s.count(a7)} (expected 1)"
s=s.replace(a7, "\n"+buysub+"\n\n---\n"+a7, 1)
assert s.count("Syndicate Delivery - the BUY side")+s.count("Syndicate Delivery — the BUY side")==1, "BUY subsection insert failed"
open(p,"w",encoding="utf-8").write(s)
print("design.md: Syndicate delivery (BUY) + supersede banner")

p2="docs/phase-1-tuning.md"; t=open(p2,encoding="utf-8").read()
tl="- **Transit ticks per edge** `[PROP]`: **2** on an open edge, **1** on a secured (owned) edge — territory security's mechanical payoff."
assert t.count(tl)==1, f"phase-1-tuning: transit-line anchor count={t.count(tl)} (expected 1)"
t=t.replace(tl, tl+"\n"+tune, 1)
assert t.count("Syndicate craft speed")==1, "craft-speed insert failed"
open(p2,"w",encoding="utf-8").write(t)
print("phase-1-tuning.md: Syndicate craft speed 300 ticks/hex")
PYEOF

# --- 2. commit (NO push) ---
git add docs/design.md docs/phase-1-tuning.md
git commit -m "docs: Syndicate BUY delivery model (scheduled deposit, straight-line, vanish-on-loss) + craft speed

Rule the BUY side of the Exchange as a scheduled delivery, not a simulated shipment:
on BUY the engine resolves the nearest waystation, computes arrivalTick = buyTick +
ceil(hexDistance x CRAFT_SPEED), debits qty*price now (single price #43, no fee),
records a pending delivery {cargo, destinationSystemId, arrivalTick} in state.shipments,
and deposits it on arrival. Destination lost in flight -> goods vanish (conservation-
clean, cash already spent). Persistence is the mid-flight handling (absolute arrival
tick). Two-tier transport boundary named: Syndicate = straight line, no risk/tolls/
routing (this slice); guild-routed = Phase 4. Craft speed 300 ticks/hex [FIRST-CUT].
Supersede the old SELL-side Syndicate-hauling model (SELL is instant, sec 5); flag the
instant-SELL vs no-free-movement / vehicle-gate tension as an open thread, not resolved."

echo; echo "Done. Review: git show --stat HEAD ; then: git push origin main"
